CREATE SEQUENCE [dbo].[catalog_hilo] AS BIGINT START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE [dbo].[catalog_brand_hilo] AS BIGINT START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE [dbo].[catalog_type_hilo] AS BIGINT START WITH 1 INCREMENT BY 10;
