spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=Microsoft.eShopOnContainers.Services.CatalogDb;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    show-sql: true

  flyway:
    enabled: true

logging:
  level:
    com.eshop.catalog: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource: DEBUG
