spring:
  application:
    name: eshop-legacy-webforms

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  thymeleaf:
    cache: false

app:
  use-mock-data: ${USE_MOCK_DATA:true}
  use-customization-data: ${USE_CUSTOMIZATION_DATA:false}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: when-authorized

server:
  port: ${SERVER_PORT:8080}
